#!/bin/bash

rm -f labels.txt 
rm -f handnumber.txt 
rm -f lasthandwin.txt 
rm -f newcount.txt 
rm -f streakcount.txt 
rm -f featuretable.txt
rm -f sum10.txt
rm -f sum20.txt
rm -f sum30.txt
rm -f player10file.txt
rm -f player20file.txt
rm -f player30file.txt
rm -f sidestreakfile.txt
rm -f playerrowfile.txt
rm -f bankrowfile.txt
rm -f sixtrackfeatures.txt
