#!/bin/bash

run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
sleep 1
run
